In [1]:
create_membership_table = """
create table membership(
    membership_id bigint,
    points int,
    points_redeemed int,
    expiry date,
    tier varchar(256),
    primary key (membership_id)
);
"""


create_user_table = """
create table user(
    nric_id varchar(256),
    name varchar(256),
    country varchar(256),
    email varchar(256),
    phone varchar(256),
    type varchar(256),
    password varchar(256),
    membership_id bigint,
    primary key (nric_id),
    foreign key (membership) (membershipid),
    
);
"""

create_schedule_table = """
create table schedule(
    schedule_id bigint primary,
    arrival_airport varchar(256),
    arrival_datetime date,
    depart_airport varchar(256),
    depart_datetime date,
    print int
);

"""

create_aircraft_table = """
create table aircraft(
    aircraft_id varchar(256) primary,
    model varchar(256),
    manufacturer varchar(256),
    capacity int
)I ;
"""


create_flight_table = """
create table flight(
    flight_id varchar(256) primary,
    aircraft_id varchar(256) foreign references aircraft(aircraft_id)
);
"""


create_seat_table = """
create table seat(
    seat_id varchar(2) primary,
    travel_class varchar(256),
    flight_id varchar(256) foreign references flight(flight_id),
)
"""

create_flight_schedule_table = """
create table flightschedule(
    flight_schedule_id bigint primary,
    schedule_id bigint foreign references schedule(schedule_id),
    flight_id varchar(256)foreign references flight(flight_id)
);

"""

create_booking_table = """
create table booking(
    booking_id bigint primary,
    nric_id varchar(256) foreign references user(nric_id),
    flight_schedule_id bigint foreign references  flightschedule(flight_schedule_id)
);
"""


create_availability_table = """
create table availability(
    availability bool,
    seat_id varchar(2) foreign references seat(seat_id),
    flight_schedule_id bigint foreign references  flightschedule(flight_schedule_id)
    primary key (seat_id, flight_schedule_id)
);
"""

create_table = [create_user_table, create_membership_table, create_schedule_table, 
                create_aircraft_table, create_flight_table, 
                create_seat_table, create_flight_schedule_table,
                create_booking_table, create_availability_table
               ]